import AppKit

/// Polls NSPasteboard.general.changeCount (macOS has no change notification).
/// Reading one integer twice a second is the standard approach and costs nothing measurable.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()
    private var timer: Timer?
    private var lastCount = NSPasteboard.general.changeCount
    private var locked = false
    var onChange: ((ClipItem) -> Void)?

    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    /// Apps whose copies are secrets by default. Most password managers mark their copies with the
    /// "concealed" pasteboard type above; Apple's Passwords app does not, so the source app is checked too.
    static func isPasswordManager(_ bundleID: String?) -> Bool {
        guard let id = bundleID?.lowercased() else { return false }
        let known = ["com.apple.passwords", "com.apple.keychainaccess", "com.1password.1password", "com.agilebits.onepassword7",
                     "com.agilebits.onepassword-osx", "com.bitwarden.desktop", "org.keepassxc.keepassxc", "in.sinew.enpass-desktop",
                     "com.lastpass.lastpass", "com.dashlane.dashlane", "com.nordpass.macos", "me.proton.pass.macos"]
        if known.contains(id) { return true }
        return ["password", "keepass", "bitwarden", "enpass", "dashlane", "lastpass", "nordpass", "strongbox", "protonpass"].contains { id.contains($0) }
    }

    private init() {
        let dnc = DistributedNotificationCenter.default()
        dnc.addObserver(forName: .init("com.apple.screenIsLocked"), object: nil, queue: .main) { [weak self] _ in
            MainActor.assumeIsolated { self?.locked = true }
        }
        dnc.addObserver(forName: .init("com.apple.screenIsUnlocked"), object: nil, queue: .main) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.locked = false
                self?.lastCount = NSPasteboard.general.changeCount   // ignore whatever happened while locked
            }
        }
    }

    func start() {
        guard timer == nil else { return }
        lastCount = NSPasteboard.general.changeCount
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        t.tolerance = 0.2
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let pb = NSPasteboard.general
        let count = pb.changeCount
        guard count != lastCount else { return }
        lastCount = count
        guard !locked, !Preferences.shared.monitoringPaused else { return }
        if let item = ingest(pb) {
            if item.kind == .text || item.kind == .url { ShelfPanelController.shared.model.noteWelcomeTried("copy") }
            onChange?(item)
        }
    }

    /// Reads the current pasteboard into the store. Returns the resulting item (new or bumped).
    @discardableResult
    func ingest(_ pb: NSPasteboard) -> ClipItem? {
        let types = pb.types ?? []
        if types.contains(PasteboardWriter.marker), let id = pb.string(forType: PasteboardWriter.marker) {
            ClipStore.shared.bump(id)
            return ClipStore.shared.items.first
        }
        if Self.skipTypes.contains(where: types.contains) { return nil }
        let store = ClipStore.shared
        let source = ClipStore.Source.frontmost
        if !Preferences.shared.recordPasswordManagers, Self.isPasswordManager(source.bundleID) { return nil }

        let hasBitmap = types.contains(.png) || types.contains(.tiff)
        let urls = (pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]) ?? []
        // Other screenshot tools (WeChat, Feishu, CleanShot…) put the picture on the board together with a file URL
        // to their own temp copy. That is a picture, not a "file": keep the bitmap so it gets a thumbnail and OCR.
        if hasBitmap, urls.isEmpty || Self.isScreenshotHandoff(urls),
           let png = pb.data(forType: .png) ?? pb.data(forType: .tiff).flatMap(Self.pngFromTIFF) {
            return store.insertImage(png: png, source: source)
        }
        if let one = urls.first, urls.count == 1, Self.isImageFile(one), Self.isTemporary(one),
           let data = try? Data(contentsOf: one), let png = Screenshotter.pngData(fromImageBytes: data) {
            return store.insertImage(png: png, source: source)      // tool copied only a temp file: same thing
        }
        if !urls.isEmpty { return store.insertFiles(urls, source: source) }
        if let s = pb.string(forType: .string) {
            return store.insertText(s, rtf: pb.data(forType: .rtf), source: source)
        }
        if let s = pb.string(forType: .URL) {
            return store.insertText(s, rtf: nil, source: source)
        }
        return nil
    }

    /// Bitmap plus exactly one image file: a screenshot handed over. (Finder copies files without bitmap data.)
    private static func isScreenshotHandoff(_ urls: [URL]) -> Bool { urls.count == 1 && isImageFile(urls[0]) }
    private static func isImageFile(_ u: URL) -> Bool {
        ["png", "jpg", "jpeg", "tiff", "tif", "heic", "gif", "webp", "bmp"].contains(u.pathExtension.lowercased())
    }
    private static func isTemporary(_ u: URL) -> Bool {
        let p = u.path
        return p.contains("/T/") || p.hasPrefix("/tmp") || p.hasPrefix("/private/tmp") || p.contains("/Caches/") || p.contains("/Library/Containers/")
    }
    private static func pngFromTIFF(_ tiff: Data) -> Data? {
        // NSBitmapImageRep keeps the embedded profile when re-encoding.
        NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
    }
}
